"""empty message

Revision ID: 06b44e4e7480
Revises: 4a8c99b68aa9
Create Date: 2025-07-03 05:25:55.619590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b44e4e7480'
down_revision: Union[str, None] = '4a8c99b68aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fromme', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('users', 'checked_resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('checked_resume', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'fromme')
    # ### end Alembic commands ###
