"""empty message

Revision ID: 190425d1e537
Revises: aaf55652050f
Create Date: 2025-01-15 00:18:50.868674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190425d1e537'
down_revision: Union[str, None] = 'aaf55652050f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('budget_from', sa.Integer(), nullable=True),
    sa.Column('budget_to', sa.Integer(), nullable=True),
    sa.Column('deadline_days', sa.Integer(), nullable=True),
    sa.Column('qty_freelancers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('all_auto_responses', sa.Boolean(), nullable=True))
    # op.drop_column('tasks', 'required_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('required_comments', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'all_auto_responses')
    op.drop_table('auto_responses')
    # ### end Alembic commands ###
