"""SchedulerTask add interval

Revision ID: 22383bc491f2
Revises: 75ea23e55882
Create Date: 2024-12-08 16:19:06.048719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22383bc491f2'
down_revision: Union[str, None] = '75ea23e55882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_tasks', sa.Column('interval_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_tasks', 'interval_hours')
    # ### end Alembic commands ###
