"""fk segments

Revision ID: 26ccf2222873
Revises: c25b8b804ca5
Create Date: 2025-02-02 10:43:43.887677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ccf2222873'
down_revision: Union[str, None] = 'c25b8b804ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_segments', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_segments', 'segments', ['segment_id'], ['id'])
    op.drop_column('user_segments', 'segment')
    op.drop_column('users', 'segments_processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('segments_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_segments', sa.Column('segment', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_segments', type_='foreignkey')
    op.drop_column('user_segments', 'segment_id')
    # ### end Alembic commands ###
