"""empty message

Revision ID: 2a7f635ed90b
Revises: 8019eccb97ae
Create Date: 2024-12-12 20:26:20.251993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7f635ed90b'
down_revision: Union[str, None] = '8019eccb97ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_token', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_token', 'title')
    # ### end Alembic commands ###
