"""segments

Revision ID: 2e6c6dbfa04d
Revises: 22b6194c881e
Create Date: 2025-02-01 21:11:23.216896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6c6dbfa04d'
down_revision: Union[str, None] = '22b6194c881e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('claimed_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('segments_processed', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('segments_processed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('segments_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'segments_processed')
    op.drop_column('subscriptions', 'segments_processed')
    op.drop_column('contracts', 'segments_processed')
    op.drop_table('user_segments')
    op.drop_table('segments')
    # ### end Alembic commands ###
