"""add client_id to loyalty_points

Revision ID: 30827213e43c
Revises: 42c0c406e6f2
Create Date: 2025-02-26 10:47:11.036564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30827213e43c'
down_revision: Union[str, None] = '42c0c406e6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_points', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'loyalty_points', 'users', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loyalty_points', type_='foreignkey')
    op.drop_column('loyalty_points', 'client_id')
    # ### end Alembic commands ###
