"""User model add chat_id and owner_id

Revision ID: 3260311082f0
Revises: 8424a0612d3d
Create Date: 2024-08-27 15:27:00.745943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3260311082f0'
down_revision: Union[str, None] = '8424a0612d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    op.drop_column('users', 'owner_id')
    # ### end Alembic commands ###
