"""initial

Revision ID: 379d72d426d7
Revises: 4989e7fa427b
Create Date: 2024-12-06 13:07:29.258422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379d72d426d7'
down_revision: Union[str, None] = '4989e7fa427b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_tasks', sa.Column('method_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_tasks', 'method_name')
    # ### end Alembic commands ###
