"""empty message

Revision ID: 477052764af6
Revises: ba5d925f52d8
Create Date: 2024-01-01 15:03:16.545044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477052764af6'
down_revision: Union[str, None] = 'ba5d925f52d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_windows_client', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_windows_client')
    # ### end Alembic commands ###
