"""initial

Revision ID: 4989e7fa427b
Revises: bc8f95dc5d70
Create Date: 2024-12-04 23:59:13.640729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4989e7fa427b'
down_revision: Union[str, None] = 'bc8f95dc5d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_tasks', sa.Column('object_id', sa.Integer(), nullable=False))
    op.add_column('scheduler_tasks', sa.Column('job_id', sa.String(), nullable=True))
    op.drop_column('scheduler_tasks', 'contract_id')
    op.add_column('tasks', sa.Column('number_of_reminders', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'number_of_reminders')
    op.add_column('scheduler_tasks', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('scheduler_tasks', 'job_id')
    op.drop_column('scheduler_tasks', 'object_id')
    # ### end Alembic commands ###
