"""empty message

Revision ID: 4a8c99b68aa9
Revises: 7357eb3d5ebf
Create Date: 2025-07-03 03:13:51.767293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8c99b68aa9'
down_revision: Union[str, None] = '7357eb3d5ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('checked_resume', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'checked_resume', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'checked_resume')
    # ### end Alembic commands ###
