"""empty message

Revision ID: 5134749d2636
Revises: 038d948f19c2
Create Date: 2023-12-31 12:52:55.692755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5134749d2636'
down_revision: Union[str, None] = '038d948f19c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('ACCEPTOFFER', 'STARTWORK', 'SUBMITWORK', 'DEADLINESPENT', 'AUTOSCREENS', 'MESSAGE', name='taskeventtype'), nullable=True),
    sa.Column('source_type', sa.Enum('WINDOWSCLIENT', 'BOT', 'WEB', name='taskeventsourcetype'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('tg_delivered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bucket_name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('task_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_event_id'], ['task_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_event')
    op.drop_table('task_events')
    # ### end Alembic commands ###
