"""Contract deadline fields.

Revision ID: 5160604838b8
Revises: d8889f12f131
Create Date: 2024-11-30 11:33:57.048198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5160604838b8'
down_revision: Union[str, None] = 'd8889f12f131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('deadline_at', sa.String(length=128), nullable=True))
    op.add_column('contracts', sa.Column('miss_deadline', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'owner_id')
    op.add_column('tasks', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'miss_deadline')
    op.drop_column('contracts', 'deadline_at')
    # ### end Alembic commands ###
