"""empty message

Revision ID: 51e51405a4c7
Revises: 477052764af6
Create Date: 2024-01-01 15:38:59.693358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e51405a4c7'
down_revision: Union[str, None] = '477052764af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('distributions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('task_event_files', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('task_event_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_event_files', 'updated_at')
    op.drop_column('task_event_files', 'created_at')
    op.drop_column('distributions', 'updated_at')
    op.drop_column('distributions', 'created_at')
    # ### end Alembic commands ###
