"""empty message

Revision ID: 56995ca90d78
Revises: 70e3718e09d8
Create Date: 2024-01-25 12:11:59.379665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56995ca90d78'
down_revision: Union[str, None] = '70e3718e09d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('deadline_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ATWORK', 'COMPLETED', 'CANCELLED', name='contractstatustype'), nullable=True),
    sa.Column('work_started_at', sa.DateTime(), nullable=True),
    sa.Column('work_stopped_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_freelancer', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'contracts', ['contract_id'], ['id'])
    op.drop_column('tasks', 'budget')
    op.drop_column('tasks', 'work_started_at')
    op.drop_column('tasks', 'work_stopped_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('work_stopped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('work_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'contract_id')
    op.drop_table('contracts')
    # ### end Alembic commands ###
