"""empty message

Revision ID: 58794ba51e79
Revises: b43e83e38f05
Create Date: 2025-01-12 21:09:11.165960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58794ba51e79'
down_revision: Union[str, None] = 'b43e83e38f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('auto_responses', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'auto_responses')
    # ### end Alembic commands ###
