"""Changed Contract.deadline_at to DateTime and User.reff_telegram_id to BigInteger

Revision ID: 5c3726c5c481
Revises: 7357eb3d5ebf
Create Date: 2025-07-03 11:06:10.081946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3726c5c481'
down_revision: Union[str, None] = '7357eb3d5ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'deadline_at',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="to_timestamp(deadline_at, 'YYYY-MM-DD HH24:MI:SS.US')"
    )
    op.alter_column('users', 'reff_telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reff_telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('contracts', 'deadline_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
