"""add/rating_models

Revision ID: 5ccb00d2eb87
Revises: c24e4c624cf5
Create Date: 2024-01-01 18:14:43.895216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccb00d2eb87'
down_revision: Union[str, None] = 'c24e4c624cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_type = sa.Enum('PLUS', 'MINUS', name='raitingchangedirection')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_direction', enum_type, nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('public_token', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'DISABLED', name='tokenstatus'),
               existing_nullable=False)

    connection = op.get_bind()
    connection.execute(
        sa.text("""
            INSERT INTO rating (user_id, score, created_at)
            SELECT id, 10, NOW()
            FROM users 
            WHERE is_registered = true
        """)
    )
    
    connection.execute(
        sa.text("""
            INSERT INTO rating_history (user_id, change_direction, score, comment, created_at)
            SELECT id, 'PLUS', 10, 'Начисление баллов за регистрацию', NOW()
            FROM users 
            WHERE is_registered = true
        """)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('public_token', 'status',
               existing_type=sa.Enum('ACTIVE', 'DISABLED', name='tokenstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('rating_history')
    op.drop_table('rating')
    enum_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
