"""empty message

Revision ID: 75ec9eb62b13
Revises: 5134749d2636
Create Date: 2023-12-31 18:26:19.970331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ec9eb62b13'
down_revision: Union[str, None] = '5134749d2636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_event_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bucket_name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('task_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_event_id'], ['task_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bucket_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_event_id'], ['task_events.id'], name='task_event_task_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_event_pkey')
    )
    op.drop_table('task_event_files')
    # ### end Alembic commands ###
