"""empty message

Revision ID: 8019eccb97ae
Revises: ed389ce1a555
Create Date: 2024-12-12 18:34:20.547209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

enum_type = sa.Enum('ACTIVE', 'DISABLED', name='tokenstatus')

# revision identifiers, used by Alembic.
revision: str = '8019eccb97ae'
down_revision: Union[str, None] = 'ed389ce1a555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_token',
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', enum_type, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_token')
    enum_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
