"""add registration_start_parameter to users

Revision ID: 871768e0ff52
Revises: c32802adbe82
Create Date: 2025-10-13 13:50:31.962940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871768e0ff52'
down_revision: Union[str, None] = 'c32802adbe82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_start_parameter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_start_parameter')
    # ### end Alembic commands ###
