"""empty message

Revision ID: 88069f0a2b2a
Revises: 58794ba51e79
Create Date: 2025-01-13 01:03:42.170331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88069f0a2b2a'
down_revision: Union[str, None] = '58794ba51e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('budget_from', sa.Integer(), nullable=True),
    sa.Column('budget_to', sa.Integer(), nullable=True),
    sa.Column('deadline_days', sa.Integer(), nullable=True),
    sa.Column('qty_freelancers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('all_auto_responses', sa.Boolean(), nullable=True))
    op.drop_column('tasks', 'auto_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('auto_responses', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'all_auto_responses')
    op.drop_table('auto_responses')
    # ### end Alembic commands ###
