"""add 2 columns into user-segments

Revision ID: 9b4a283fbe0a
Revises: d425922cf8f0
Create Date: 2025-08-13 19:20:11.720987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4a283fbe0a'
down_revision: Union[str, None] = 'd425922cf8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_segments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_segments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_segments', 'updated_at')
    op.drop_column('user_segments', 'created_at')
    # ### end Alembic commands ###
