"""Task model private content

Revision ID: a2b2cc224dc0
Revises: d660334558c8
Create Date: 2024-12-09 22:04:47.645278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b2cc224dc0'
down_revision: Union[str, None] = 'd660334558c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('private_content', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'private_content')
    # ### end Alembic commands ###
