"""empty message

Revision ID: b3e255f2093e
Revises: 56995ca90d78
Create Date: 2024-01-25 12:17:58.597812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e255f2093e'
down_revision: Union[str, None] = '56995ca90d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_contract_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'contract_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_contract_id_fkey', 'tasks', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###
