"""empty message

Revision ID: b43e83e38f05
Revises: d5e398ec3b6c
Create Date: 2025-01-12 12:57:23.164717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43e83e38f05'
down_revision: Union[str, None] = 'd5e398ec3b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'comment_freelancer')
    op.drop_column('tasks', 'required_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('required_comments', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('comment_freelancer', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
