"""empty message

Revision ID: ba5d925f52d8
Revises: 75ec9eb62b13
Create Date: 2024-01-01 14:06:32.085193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5d925f52d8'
down_revision: Union[str, None] = '75ec9eb62b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_event_files', sa.Column('key', sa.String(), nullable=True))
    op.add_column('task_event_files', sa.Column('is_uploaded', sa.Boolean(), nullable=True, default=False))
    op.drop_column('task_event_files', 'name')
    # ### end Alembic commands ###z


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_event_files', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task_event_files', 'is_uploaded')
    op.drop_column('task_event_files', 'key')
    # ### end Alembic commands ###
