"""add is_lite_offer

Revision ID: c24e4c624cf5
Revises: 2a7f635ed90b
Create Date: 2025-01-17 19:45:31.695828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24e4c624cf5'
down_revision: Union[str, None] = '190425d1e537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_lite_offer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_lite_offer')
    # ### end Alembic commands ###
