"""segments fix 1

Revision ID: c25b8b804ca5
Revises: 2e6c6dbfa04d
Create Date: 2025-02-01 21:25:21.320004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c25b8b804ca5'
down_revision: Union[str, None] = '2e6c6dbfa04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_segments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('user_segments_user_id_fkey', 'user_segments', type_='foreignkey')
    op.create_foreign_key(None, 'user_segments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_segments', type_='foreignkey')
    op.create_foreign_key('user_segments_user_id_fkey', 'user_segments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_segments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
