"""add chat_id for Task

Revision ID: d356181edc45
Revises: 7460a7e5ea0f
Create Date: 2024-08-27 17:13:43.939469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd356181edc45'
down_revision: Union[str, None] = '7460a7e5ea0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'chat_id')
    # ### end Alembic commands ###
