"""add 2 columns into user-segments

Revision ID: d425922cf8f0
Revises: b920e2958f5b
Create Date: 2025-08-13 19:05:15.739701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd425922cf8f0'
down_revision: Union[str, None] = 'b920e2958f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping columns that don't exist
    # This migration was created in error - the columns never existed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Since we didn't drop anything, we don't need to add anything back
    pass
    # ### end Alembic commands ###
