"""empty message

Revision ID: d5e398ec3b6c
Revises: dd976474aa2e
Create Date: 2025-01-11 23:42:36.241665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e398ec3b6c'
down_revision: Union[str, None] = 'dd976474aa2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('comment_freelancer', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'comment_freelancer')
    # ### end Alembic commands ###
