"""SchedulerTask add last_message_id

Revision ID: d660334558c8
Revises: 22383bc491f2
Create Date: 2024-12-09 13:07:26.005740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd660334558c8'
down_revision: Union[str, None] = '22383bc491f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_tasks', sa.Column('last_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_tasks', 'last_message_id')
    # ### end Alembic commands ###
