"""Contract evaluate field

Revision ID: d73bd778d0ac
Revises: d356181edc45
Create Date: 2024-09-02 14:22:44.086832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73bd778d0ac'
down_revision: Union[str, None] = 'd356181edc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('evaluate', sa.Integer(), nullable=True))
    op.drop_column('users', 'owner_id')
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'evaluate')
    # ### end Alembic commands ###
