"""User group add owner_id

Revision ID: d8889f12f131
Revises: d73bd778d0ac
Create Date: 2024-11-29 15:34:32.362098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8889f12f131'
down_revision: Union[str, None] = 'd73bd778d0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'chat_id')
    op.add_column('users', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'owner_id')
    op.add_column('tasks', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
