"""empty message

Revision ID: dd976474aa2e
Revises: 2a7f635ed90b
Create Date: 2025-01-11 21:31:48.075063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd976474aa2e'
down_revision: Union[str, None] = '2a7f635ed90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('required_comments', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'required_comments')
    # ### end Alembic commands ###
