"""empty message

Revision ID: e51a2add9caa
Revises: e618fd4dce6d
Create Date: 2025-01-13 23:55:38.835585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51a2add9caa'
down_revision: Union[str, None] = 'e618fd4dce6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('comment_freelancer', sa.String(length=5000), nullable=True))
    op.drop_column('contracts', 'comments_freelancer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('comments_freelancer', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'comment_freelancer')
    # ### end Alembic commands ###
