"""empty message

Revision ID: e618fd4dce6d
Revises: ee7b4acfe277
Create Date: 2025-01-13 23:34:52.731195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e618fd4dce6d'
down_revision: Union[str, None] = 'ee7b4acfe277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('comments_freelancer', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'comments_freelancer')
    # ### end Alembic commands ###
