"""Add fromme column

Revision ID: e919d647e95d
Revises: 06b44e4e7480
Create Date: 2025-07-03 06:04:16.335966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e919d647e95d'
down_revision: Union[str, None] = '06b44e4e7480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('fromme', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user_segments', sa.Column('fromme', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_segments', 'fromme')
    op.drop_column('subscriptions', 'fromme')
    # ### end Alembic commands ###
