"""Task model is_hard fields

Revision ID: ed389ce1a555
Revises: a2b2cc224dc0
Create Date: 2024-12-09 22:06:09.646647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed389ce1a555'
down_revision: Union[str, None] = 'a2b2cc224dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_hard', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_hard')
    # ### end Alembic commands ###
