"""empty message

Revision ID: ee7b4acfe277
Revises: 88069f0a2b2a
Create Date: 2025-01-13 23:08:05.197757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee7b4acfe277'
down_revision: Union[str, None] = '88069f0a2b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_responses')
    op.drop_column('tasks', 'all_auto_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('all_auto_responses', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('auto_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deadline_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qty_freelancers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='auto_responses_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='auto_responses_pkey')
    )
    # ### end Alembic commands ###
